name: Continuous Deployment
on:
  workflow_dispatch:

jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install bun dependencies
        run: bun install --frozen-lockfile

      - name: Publish NPM
        run: bun publish
