name: Continuous Integration
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint_gen_and_test:
    name: Lint, Gen and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout respository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Biome
        uses: biomejs/setup-biome@v2

      - name: Install bun dependencies
        run: bun install --frozen-lockfile

      - name: Run Biome Lint from Bun
        run: bun lint

      - name: Check gen
        run: bun gen

      - name: Run test with Bun
        run: bun test
